name: tests-tickets

on:
  pull_request:
    paths:
<<<<<<< HEAD
      - "tickets/**"

=======
      - 'tickets/**'
  
>>>>>>> 309dbba58581b76b540365d31beddefdf5e7d402
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
