name: tests-payments

on:
  pull_request:
    paths:
<<<<<<< HEAD
      - "payments/**"

=======
      - 'payments/**'
  
>>>>>>> 309dbba58581b76b540365d31beddefdf5e7d402
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
